### ISSUE TITLE
macOS build issues

### ISSUE THREAD

**Issue by Jerboa-app** [JerboaBurrow/JellyCram#54]
- [ ] app fails to load

**Comment by Jerboa-app** [comment]
```
[1;34m[LUA] [0mprocess running
=================================================================
==11478==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x607000048220 at pc 0x000104f59c86 bp 0x7ff7bb12f0d0 sp 0x7ff7bb12f0c8
WRITE of size 8 at 0x607000048220 thread T0
    #0 0x104f59c85 in JellyCramState::iteration(Hop::Object::EntityComponentSystem&, Hop::Console&, Hop::System::Physics::sCollision&, Hop::System::Physics::sPhysics&, std::__1::shared_ptr<Hop::World::AbstractWorld>, void (*)(Hop::Console&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>), unsigned char, bool) gameState.cpp:311
    #1 0x104ddb0b2 in main main.cpp:287
    #2 0x7ff80909f3a5 in start+0x795 (dyld:x86_64+0xfffffffffff5c3a5)

0x607000048220 is located 0 bytes after 80-byte region [0x6070000481d0,0x607000048220)
allocated by thread T0 here:
    #0 0x10638460d in wrap__Znwm+0x7d (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0xec60d)
    #1 0x104e16cc4 in void* std::__1::__libcpp_operator_new[abi:v160006]<unsigned long>(unsigned long) new:285
    #2 0x104e16c4c in std::__1::__libcpp_allocate[abi:v160006](unsigned long, unsigned long) new:311
    #3 0x104e2fc1c in std::__1::allocator<double>::allocate[abi:v160006](unsigned long) allocator.h:115
    #4 0x104e2f91a in std::__1::__allocation_result<std::__1::allocator_traits<std::__1::allocator<double>>::pointer> std::__1::__allocate_at_least[abi:v160006]<std::__1::allocator<double>>(std::__1::allocator<double>&, unsigned long) allocate_at_least.h:55
    #5 0x104e2ea45 in std::__1::vector<double, std::__1::allocator<double>>::__vallocate[abi:v160006](unsigned long) vector:688
    #6 0x104e2e4e6 in std::__1::vector<double, std::__1::allocator<double>>::vector(unsigned long, double const&) vector:1111
    #7 0x104e2d554 in std::__1::vector<double, std::__1::allocator<double>>::vector(unsigned long, double const&) vector:1106
    #8 0x104e2d25e in JellyCramState::JellyCramState() gameState.h:131
    #9 0x104de5d24 in JellyCramState::JellyCramState() gameState.h:89
    #10 0x104dd8ea4 in main main.cpp:158
    #11 0x7ff80909f3a5 in start+0x795 (dyld:x86_64+0xfffffffffff5c3a5)

SUMMARY: AddressSanitizer: heap-buffer-overflow gameState.cpp:311 in JellyCramState::iteration(Hop::Object::EntityComponentSystem&, Hop::Console&, Hop::System::Physics::sCollision&, Hop::System::Physics::sPhysics&, std::__1::shared_ptr<Hop::World::AbstractWorld>, void (*)(Hop::Console&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>), unsigned char, bool)
Shadow bytes around the buggy address:
  0x607000047f80: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fa fa
  0x607000048000: fa fa fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x607000048080: fd fd fd fd fd fd fd fd fd fd fa fa fa fa fd fd
  0x607000048100: fd fd fd fd fd fd fd fd fa fa fa fa 00 00 00 00
  0x607000048180: 00 00 00 00 00 fa fa fa fa fa 00 00 00 00 00 00
=>0x607000048200: 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa
  0x607000048280: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x607000048300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x607000048380: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x607000048400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x607000048480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==11478==ABORTING
```
